// sdks/kiponos-angular-sdk/examples/basic-usage.ts
/**
 * Minimal usage sketch (not a full Angular CLI app).
 * Copy patterns into your standalone Angular project.
 */
import { Component } from "@angular/core";
import {
  provideKiponos,
  injectKiponos,
  Kiponos,
  type ProvideKiponosConfig,
} from "@kiponos/angular";

// --- Node / SSR bootstrap ---
// const client = Kiponos.createFromEnv();
// await client.connect();
// provideKiponos({ client, autoConnect: false })

// --- Component ---
@Component({
  standalone: true,
  selector: "app-theme",
  template: `
    <span data-theme="{{ theme() }}">theme={{ theme() }}</span>
    <button [disabled]="!kip.ready()" (click)="toggle()">Toggle</button>
    <p>status={{ kip.status() }}</p>
  `,
})
export class ThemeComponent {
  readonly kip = injectKiponos();
  readonly theme = this.kip.value("ui/theme", { defaultValue: "dark" });

  constructor() {
    this.kip.afterValueUpdated((e) => {
      console.log("value updated", e.key, e.value);
    });
  }

  async toggle() {
    const cur = this.theme() ?? "dark";
    await this.kip.ensurePath("ui");
    await this.kip.path("ui").set("theme", cur === "dark" ? "light" : "dark");
  }
}

// Document config shape for app.config.ts
export const exampleProvideConfig: ProvideKiponosConfig = {
  // client: prebuilt,
  fromEnv: true,
  autoConnect: true,
};

void Kiponos; // silence unused when only reading this file
void provideKiponos;

// sdks/kiponos-react-sdk/examples/basic-usage.tsx
/**
 * Minimal usage sketch (not a runnable app — copy into your CRA/Vite project).
 */
import React from "react";
import {
  KiponosProvider,
  useKiponos,
  useKiponosValue,
  useAfterValueUpdated,
} from "@kiponos/react";

function ThemeBadge() {
  // Live leaf — no Context prop-drilling for "theme"
  const theme = useKiponosValue("ui/theme", { defaultValue: "dark" });
  return <span data-theme={theme}>theme={theme}</span>;
}

function ThemeToggle() {
  const kip = useKiponos();
  return (
    <button
      disabled={!kip.ready}
      onClick={() => {
        const cur = kip.getPath("ui/theme", "dark");
        void kip.path("ui").set("theme", cur === "dark" ? "light" : "dark");
      }}
    >
      Toggle theme
    </button>
  );
}

function LiveLog() {
  useAfterValueUpdated((e) => {
    console.log("value updated", e.key, e.value);
  });
  return null;
}

export function App() {
  return (
    <KiponosProvider
      profile="['MyApp']['1.0.0']['Dev']['base']"
      idToken={process.env.REACT_APP_KIPONOS_ID!}
      accessToken={process.env.REACT_APP_KIPONOS_ACCESS!}
      // serverUrl="wss://kiponos.io/api/io-kiponos-sdk"
    >
      <LiveLog />
      <ThemeBadge />
      <ThemeToggle />
    </KiponosProvider>
  );
}
